apiVersion: v1
kind: Service
metadata:
  name: app-gateway
spec:
  type: NodePort  # Or ClusterIP if only needed inside cluster
  selector:
    app: app-gateway
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30080  # Optional: choose your own NodePort or leave blank for auto-assigned
