apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gateway
  template:
    metadata:
      labels:
        app: app-gateway
    spec:
      containers:
        - name: app-gateway
          image: app-gateway:1.0
          ports:
            - containerPort: 8082
